services:
  backend:
    image: node:22-bullseye
    working_dir: /app
    command: sh -c "npm install && npm run server"
    volumes:
      - ./:/app
      - backend_node_modules:/app/node_modules
    environment:
      JWT_SECRET: dev-secret
    ports:
      - "3001:3001"

  frontend:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5174:5173"
    environment:
      VITE_DEV_SERVER_HOST: 0.0.0.0
      VITE_DEV_SERVER_PORT: 5173
      VITE_API_PROXY: http://backend:3001

volumes:
  backend_node_modules:
  frontend_node_modules:
