FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN apk add --no-cache python3 make g++ \
  && npm install \
  && apk del python3 make g++

COPY . .

RUN npm run build

FROM nginx:1.28-alpine

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
